### DISCUSSION TITLE
Automate PyPI release through GitHub Actions -- set secrets

### DISCUSSION THREAD

**Discussion by felix-seifert** [csgoh/roadmapper#91] [General]
I am about to automate the whole release process. In my recent PRs #95, #96, #97, #98, #99 and #100, I implemented the process to bump the version and trigger a release on PyPI and GitHub for every new tag.

For releasing the lib on PyPI, I want to use the workflow shown in the three .bat files, i.e. I just want to use Twine. I translated this into a GitHub Actions workflow in #100. For this workflow to succeed, I require the credentials for PyPI. You do not have to leak the credentials to me; I can use them from GitHub's secrets. You just have to store them there. As I assume that you use username and password, can you persist the following GitHub secrets: `PYPI_USERNAME` and `PYPI_PASSWORD`?

The following steps will then be the ones used for releasing to PyPI.

```
      - name: Build dist
        run: |
          python -m build

      - name: Test dist
        run: |
          python -m twine check dist/*

      - name: Deploy dist
        run: |
          python -m twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
```
